name: Build and publish application

on: 
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup dotnet 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - id: previous_version
        run: |
          echo "previous-version=$(gh repo view --json latestRelease --jq '.latestRelease.tagName')" >> $GITHUB_OUTPUT

      - name: Build for Linux
        run: |
          dotnet publish MercuryModder --runtime linux-x64 -o "./builds/MercuryModder-linux-x64"
          zip -r "MercuryModder-linux-x64.zip" "./builds/MercuryModder-linux-x64"
      
      - name: Build for Windows
        run: |
          dotnet publish MercuryModder --runtime win-x64 -o "./builds/MercuryModder-windows-x64"
          zip -r "MercuryModder-windows-x64.zip" "./builds/MercuryModder-windows-x64"

      - name: Create Release
        uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: "MercuryModder-linux-x64.zip, MercuryModder-windows-x64.zip"
          generateReleaseNotes: true
          generateReleaseNotesPreviousTag: ${{ steps.previous_version.outputs.previous-version }}
          makeLatest: true

